require('dotenv').config();

// Required variables check
function requireEnv(name) {
    const val = process.env[name];
    if (!val) {
        console.error(`[config] ❌ Missing required env variable: ${name}`);
        process.exit(1);
    }
    return val;
}

const PAIRS = [
    { n: 'USOIL',   s: 'USO'     },
    { n: 'US500',   s: 'SPY'     },
    { n: 'US100',   s: 'QQQ'     },
    { n: 'US30',    s: 'DIA'     },
    { n: 'GER40',   s: 'EWG'     },
    { n: 'UK100',   s: 'EWU'     },
    { n: 'JPN225',  s: 'EWJ'     },
    { n: 'EURUSD',  s: 'EUR/USD' },
    { n: 'GBPUSD',  s: 'GBP/USD' },
    { n: 'USDJPY',  s: 'USD/JPY' },
    { n: 'USDCHF',  s: 'USD/CHF' },
    { n: 'USDCAD',  s: 'USD/CAD' },
    { n: 'AUDUSD',  s: 'AUD/USD' },
    { n: 'NZDUSD',  s: 'NZD/USD' },
    { n: 'EURJPY',  s: 'EUR/JPY' },
    { n: 'GBPJPY',  s: 'GBP/JPY' },
    { n: 'AUDJPY',  s: 'AUD/JPY' },
    { n: 'NZDJPY',  s: 'NZD/JPY' },
    { n: 'CADJPY',  s: 'CAD/JPY' },
    { n: 'CHFJPY',  s: 'CHF/JPY' },
    { n: 'EURGBP',  s: 'EUR/GBP' },
    { n: 'EURAUD',  s: 'EUR/AUD' },
    { n: 'EURCAD',  s: 'EUR/CAD' },
    { n: 'EURCHF',  s: 'EUR/CHF' },
    { n: 'GBPAUD',  s: 'GBP/AUD' },
    { n: 'GBPCAD',  s: 'GBP/CAD' },
    { n: 'GBPCHF',  s: 'GBP/CHF' },
    { n: 'AUDCAD',  s: 'AUD/CAD' },
    { n: 'AUDCHF',  s: 'AUD/CHF' },
    { n: 'AUDNZD',  s: 'AUD/NZD' },
    { n: 'NZDCAD',  s: 'NZD/CAD' },
    { n: 'NZDCHF',  s: 'NZD/CHF' },
    { n: 'CADCHF',  s: 'CAD/CHF' },
    { n: 'XAUUSD',  s: 'XAU/USD' },
    // ────── Crypto (100 coins) ──────
    { n: 'BTCUSDT', s: 'BINANCE:BTCUSDT', isCrypto: true },
    { n: 'ETHUSDT', s: 'BINANCE:ETHUSDT', isCrypto: true },
    { n: 'SOLUSDT', s: 'BINANCE:SOLUSDT', isCrypto: true },
    { n: 'BNBUSDT', s: 'BINANCE:BNBUSDT', isCrypto: true },
    { n: 'XRPUSDT', s: 'BINANCE:XRPUSDT', isCrypto: true },
    { n: 'ADAUSDT', s: 'BINANCE:ADAUSDT', isCrypto: true },
    { n: 'AVAXUSDT', s: 'BINANCE:AVAXUSDT', isCrypto: true },
    { n: 'LINKUSDT', s: 'BINANCE:LINKUSDT', isCrypto: true },
    { n: 'TRXUSDT', s: 'BINANCE:TRXUSDT', isCrypto: true },
    { n: 'MATICUSDT', s: 'BINANCE:MATICUSDT', isCrypto: true },
    { n: 'LTCUSDT', s: 'BINANCE:LTCUSDT', isCrypto: true },
    { n: 'TONUSDT', s: 'BINANCE:TONUSDT', isCrypto: true },
    { n: 'BCHUSDT', s: 'BINANCE:BCHUSDT', isCrypto: true },
    { n: 'UNIUSDT', s: 'BINANCE:UNIUSDT', isCrypto: true },
    { n: 'ATOMUSDT', s: 'BINANCE:ATOMUSDT', isCrypto: true },
    { n: 'XLMUSDT', s: 'BINANCE:XLMUSDT', isCrypto: true },
    { n: 'ETCUSDT', s: 'BINANCE:ETCUSDT', isCrypto: true },
    { n: 'NEARUSDT', s: 'BINANCE:NEARUSDT', isCrypto: true },
    { n: 'FETUSDT', s: 'BINANCE:FETUSDT', isCrypto: true },
    { n: 'RNDRUSDT', s: 'BINANCE:RNDRUSDT', isCrypto: true },
    { n: 'TAOUSDT', s: 'BINANCE:TAOUSDT', isCrypto: true },
    { n: 'GRTUSDT', s: 'BINANCE:GRTUSDT', isCrypto: true },
    { n: 'ARKMUSDT', s: 'BINANCE:ARKMUSDT', isCrypto: true },
    { n: 'AGIXUSDT', s: 'BINANCE:AGIXUSDT', isCrypto: true },
    { n: 'OCEANUSDT', s: 'BINANCE:OCEANUSDT', isCrypto: true },
    { n: 'WLDUSDT', s: 'BINANCE:WLDUSDT', isCrypto: true },
    { n: 'AKTUSDT', s: 'BINANCE:AKTUSDT', isCrypto: true },
    { n: 'NMRUSDT', s: 'BINANCE:NMRUSDT', isCrypto: true },
    { n: 'PHBUSDT', s: 'BINANCE:PHBUSDT', isCrypto: true },
    { n: 'CQTUSDT', s: 'BINANCE:CQTUSDT', isCrypto: true },
    { n: 'ORAIUSDT', s: 'BINANCE:ORAIUSDT', isCrypto: true },
    { n: 'VRAUSDT', s: 'BINANCE:VRAUSDT', isCrypto: true },
    { n: 'ONDOUSDT', s: 'BINANCE:ONDOUSDT', isCrypto: true },
    { n: 'PENDLEUSDT', s: 'BINANCE:PENDLEUSDT', isCrypto: true },
    { n: 'MKRUSDT', s: 'BINANCE:MKRUSDT', isCrypto: true },
    { n: 'AAVEUSDT', s: 'BINANCE:AAVEUSDT', isCrypto: true },
    { n: 'COMPUSDT', s: 'BINANCE:COMPUSDT', isCrypto: true },
    { n: 'CRVUSDT', s: 'BINANCE:CRVUSDT', isCrypto: true },
    { n: 'SNXUSDT', s: 'BINANCE:SNXUSDT', isCrypto: true },
    { n: 'LDOUSDT', s: 'BINANCE:LDOUSDT', isCrypto: true },
    { n: 'GMXUSDT', s: 'BINANCE:GMXUSDT', isCrypto: true },
    { n: 'CFGUSDT', s: 'BINANCE:CFGUSDT', isCrypto: true },
    { n: 'MNTUSDT', s: 'BINANCE:MNTUSDT', isCrypto: true },
    { n: 'RSRUSDT', s: 'BINANCE:RSRUSDT', isCrypto: true },
    { n: 'STXUSDT', s: 'BINANCE:STXUSDT', isCrypto: true },
    { n: 'PYTHUSDT', s: 'BINANCE:PYTHUSDT', isCrypto: true },
    { n: 'JUPUSDT', s: 'BINANCE:JUPUSDT', isCrypto: true },
    { n: 'IMXUSDT', s: 'BINANCE:IMXUSDT', isCrypto: true },
    { n: 'SANDUSDT', s: 'BINANCE:SANDUSDT', isCrypto: true },
    { n: 'MANAUSDT', s: 'BINANCE:MANAUSDT', isCrypto: true },
    { n: 'AXSUSDT', s: 'BINANCE:AXSUSDT', isCrypto: true },
    { n: 'GALAUSDT', s: 'BINANCE:GALAUSDT', isCrypto: true },
    { n: 'BEAMUSDT', s: 'BINANCE:BEAMUSDT', isCrypto: true },
    { n: 'YGGUSDT', s: 'BINANCE:YGGUSDT', isCrypto: true },
    { n: 'ILVUSDT', s: 'BINANCE:ILVUSDT', isCrypto: true },
    { n: 'BIGTIMEUSDT', s: 'BINANCE:BIGTIMEUSDT', isCrypto: true },
    { n: 'PYRUSDT', s: 'BINANCE:PYRUSDT', isCrypto: true },
    { n: 'ENJUSDT', s: 'BINANCE:ENJUSDT', isCrypto: true },
    { n: 'VOXELUSDT', s: 'BINANCE:VOXELUSDT', isCrypto: true },
    { n: 'APEUSDT', s: 'BINANCE:APEUSDT', isCrypto: true },
    { n: 'TIAUSDT', s: 'BINANCE:TIAUSDT', isCrypto: true },
    { n: 'SEIUSDT', s: 'BINANCE:SEIUSDT', isCrypto: true },
    { n: 'SUIUSDT', s: 'BINANCE:SUIUSDT', isCrypto: true },
    { n: 'APTUSDT', s: 'BINANCE:APTUSDT', isCrypto: true },
    { n: 'ARBUSDT', s: 'BINANCE:ARBUSDT', isCrypto: true },
    { n: 'OPUSDT', s: 'BINANCE:OPUSDT', isCrypto: true },
    { n: 'STRKUSDT', s: 'BINANCE:STRKUSDT', isCrypto: true },
    { n: 'KASUSDT', s: 'BINANCE:KASUSDT', isCrypto: true },
    { n: 'XMRUSDT', s: 'BINANCE:XMRUSDT', isCrypto: true },
    { n: 'EOSUSDT', s: 'BINANCE:EOSUSDT', isCrypto: true },
    { n: 'FTMUSDT', s: 'BINANCE:FTMUSDT', isCrypto: true },
    { n: 'HBARUSDT', s: 'BINANCE:HBARUSDT', isCrypto: true },
    { n: 'FILUSDT', s: 'BINANCE:FILUSDT', isCrypto: true },
    { n: 'DASHUSDT', s: 'BINANCE:DASHUSDT', isCrypto: true },
    { n: 'ZECUSDT', s: 'BINANCE:ZECUSDT', isCrypto: true },
    { n: 'THETAUSDT', s: 'BINANCE:THETAUSDT', isCrypto: true },
    { n: 'KLAYUSDT', s: 'BINANCE:KLAYUSDT', isCrypto: true },
    { n: 'EGLDUSDT', s: 'BINANCE:EGLDUSDT', isCrypto: true },
    { n: 'NEOUSDT', s: 'BINANCE:NEOUSDT', isCrypto: true },
    { n: 'QTUMUSDT', s: 'BINANCE:QTUMUSDT', isCrypto: true },
    { n: 'IOTAUSDT', s: 'BINANCE:IOTAUSDT', isCrypto: true },
    { n: 'KAVAUSDT', s: 'BINANCE:KAVAUSDT', isCrypto: true },
    { n: 'MINAUSDT', s: 'BINANCE:MINAUSDT', isCrypto: true },
    { n: 'ROSEUSDT', s: 'BINANCE:ROSEUSDT', isCrypto: true },
    { n: 'CFXUSDT', s: 'BINANCE:CFXUSDT', isCrypto: true },
    { n: 'LPTUSDT', s: 'BINANCE:LPTUSDT', isCrypto: true },
    { n: 'RUNEUSDT', s: 'BINANCE:RUNEUSDT', isCrypto: true },
    { n: 'FLOWUSDT', s: 'BINANCE:FLOWUSDT', isCrypto: true },
    { n: 'CHZUSDT', s: 'BINANCE:CHZUSDT', isCrypto: true },
    { n: 'SNXUSDT', s: 'BINANCE:SNXUSDT', isCrypto: true },
    { n: 'DYDXUSDT', s: 'BINANCE:DYDXUSDT', isCrypto: true },
    { n: 'GLMRUSDT', s: 'BINANCE:GLMRUSDT', isCrypto: true },
    { n: 'ENSUSDT', s: 'BINANCE:ENSUSDT', isCrypto: true },
    { n: 'GALUSDT', s: 'BINANCE:GALUSDT', isCrypto: true },
    { n: 'ANKRUSDT', s: 'BINANCE:ANKRUSDT', isCrypto: true },
    { n: 'SKLUSDT', s: 'BINANCE:SKLUSDT', isCrypto: true },
    { n: 'IOTXUSDT', s: 'BINANCE:IOTXUSDT', isCrypto: true },
    { n: 'LQTYUSDT', s: 'BINANCE:LQTYUSDT', isCrypto: true },
    { n: 'API3USDT', s: 'BINANCE:API3USDT', isCrypto: true },
    { n: 'QNTUSDT', s: 'BINANCE:QNTUSDT', isCrypto: true },
];

// CRYPTO_PAIRS ko derive karo config se
const CRYPTO_PAIRS = PAIRS.filter(p => p.isCrypto).map(p => p.n);

const KEYS = [
    process.env.TD_KEY_1,  process.env.TD_KEY_2,  process.env.TD_KEY_3,
    process.env.TD_KEY_4,  process.env.TD_KEY_5,  process.env.TD_KEY_6,
    process.env.TD_KEY_7,  process.env.TD_KEY_8,  process.env.TD_KEY_9,
    process.env.TD_KEY_10, process.env.TD_KEY_11, process.env.TD_KEY_12,
    process.env.TD_KEY_13, process.env.TD_KEY_14, process.env.TD_KEY_15,
    process.env.TD_KEY_16
].filter(Boolean);

if (KEYS.length === 0) {
    console.error('[config] ❌ Koi bhi TD_KEY_* env variable nahi mili — scan nahi chalega!');
    process.exit(1);
}

console.log(`[config] ✅ ${KEYS.length} API keys loaded.`);

module.exports = {
    BOT_TOKEN:    requireEnv('BOT_TOKEN'),
    CHAT_ID:      requireEnv('CHAT_ID'),
    FIREBASE_URL: requireEnv('FIREBASE_URL'),
    KEYS,
    PAIRS,
    CRYPTO_PAIRS
};
