require('dotenv').config();

function requireEnv(name) {
    const val = process.env[name];
    if (!val) {
        console.error(`[config] ❌ Missing required env variable: ${name}`);
        process.exit(1);
    }
    return val;
}

const PAIRS = [
    // Forex & Indices
    { n: 'USOIL',   s: 'USO'     },
    { n: 'US500',   s: 'SPY'     },
    { n: 'US100',   s: 'QQQ'     },
    { n: 'US30',    s: 'DIA'     },
    { n: 'GER40',   s: 'EWG'     },
    { n: 'UK100',   s: 'EWU'     },
    { n: 'JPN225',  s: 'EWJ'     },
    { n: 'EURUSD',  s: 'EUR/USD' },
    { n: 'GBPUSD',  s: 'GBP/USD' },
    { n: 'USDJPY',  s: 'USD/JPY' },
    { n: 'USDCHF',  s: 'USD/CHF' },
    { n: 'USDCAD',  s: 'USD/CAD' },
    { n: 'AUDUSD',  s: 'AUD/USD' },
    { n: 'NZDUSD',  s: 'NZD/USD' },
    { n: 'EURJPY',  s: 'EUR/JPY' },
    { n: 'GBPJPY',  s: 'GBP/JPY' },
    { n: 'AUDJPY',  s: 'AUD/JPY' },
    { n: 'NZDJPY',  s: 'NZD/JPY' },
    { n: 'CADJPY',  s: 'CAD/JPY' },
    { n: 'CHFJPY',  s: 'CHF/JPY' },
    { n: 'EURGBP',  s: 'EUR/GBP' },
    { n: 'EURAUD',  s: 'EUR/AUD' },
    { n: 'EURCAD',  s: 'EUR/CAD' },
    { n: 'EURCHF',  s: 'EUR/CHF' },
    { n: 'GBPAUD',  s: 'GBP/AUD' },
    { n: 'GBPCAD',  s: 'GBP/CAD' },
    { n: 'GBPCHF',  s: 'GBP/CHF' },
    { n: 'AUDCAD',  s: 'AUD/CAD' },
    { n: 'AUDCHF',  s: 'AUD/CHF' },
    { n: 'AUDNZD',  s: 'AUD/NZD' },
    { n: 'NZDCAD',  s: 'NZD/CAD' },
    { n: 'NZDCHF',  s: 'NZD/CHF' },
    { n: 'CADCHF',  s: 'CAD/CHF' },
    { n: 'XAUUSD',  s: 'XAU/USD' },
    { n: 'BTCUSD',  s: 'BTC/USD', isCrypto: true },
    { n: 'ETHUSD',  s: 'ETH/USD', isCrypto: true },

    // ── Additional 98 Crypto Pairs ──
    { n: 'LTCUSD',  s: 'LTC/USD', isCrypto: true },
    { n: 'BCHUSD',  s: 'BCH/USD', isCrypto: true },
    { n: 'XRPUSD',  s: 'XRP/USD', isCrypto: true },
    { n: 'ADAUSD',  s: 'ADA/USD', isCrypto: true },
    { n: 'DOTUSD',  s: 'DOT/USD', isCrypto: true },
    { n: 'LINKUSD', s: 'LINK/USD', isCrypto: true },
    { n: 'UNIUSD',  s: 'UNI/USD', isCrypto: true },
    { n: 'SOLUSD',  s: 'SOL/USD', isCrypto: true },
    { n: 'MATICUSD', s: 'MATIC/USD', isCrypto: true },
    { n: 'AVAXUSD', s: 'AVAX/USD', isCrypto: true },
    { n: 'ATOMUSD', s: 'ATOM/USD', isCrypto: true },
    { n: 'FILUSD',  s: 'FIL/USD', isCrypto: true },
    { n: 'VETUSD',  s: 'VET/USD', isCrypto: true },
    { n: 'ETCUSD',  s: 'ETC/USD', isCrypto: true },
    { n: 'TRXUSD',  s: 'TRX/USD', isCrypto: true },
    { n: 'XLMUSD',  s: 'XLM/USD', isCrypto: true },
    { n: 'ICPUSD',  s: 'ICP/USD', isCrypto: true },
    { n: 'THETAUSD', s: 'THETA/USD', isCrypto: true },
    { n: 'XTZUSD',  s: 'XTZ/USD', isCrypto: true },
    { n: 'EOSUSD',  s: 'EOS/USD', isCrypto: true },
    { n: 'SANDUSD', s: 'SAND/USD', isCrypto: true },
    { n: 'MANAUSD', s: 'MANA/USD', isCrypto: true },
    { n: 'DOGEUSD', s: 'DOGE/USD', isCrypto: true },
    { n: 'SHIBUSD', s: 'SHIB/USD', isCrypto: true },
    { n: 'PEPEUSD', s: 'PEPE/USD', isCrypto: true },
    { n: 'BONKUSD', s: 'BONK/USD', isCrypto: true },
    { n: 'FLOKIUSD', s: 'FLOKI/USD', isCrypto: true },
    { n: 'WIFUSD',  s: 'WIF/USD', isCrypto: true },
    { n: 'GRTUSD',  s: 'GRT/USD', isCrypto: true },
    { n: 'ENJUSD',  s: 'ENJ/USD', isCrypto: true },
    { n: 'CHZUSD',  s: 'CHZ/USD', isCrypto: true },
    { n: 'BATUSD',  s: 'BAT/USD', isCrypto: true },
    { n: 'ZRXUSD',  s: 'ZRX/USD', isCrypto: true },
    { n: 'OMGUSD',  s: 'OMG/USD', isCrypto: true },
    { n: 'DASHUSD', s: 'DASH/USD', isCrypto: true },
    { n: 'ZECUSD',  s: 'ZEC/USD', isCrypto: true },
    { n: 'BTGUSD',  s: 'BTG/USD', isCrypto: true },
    { n: 'DCRUSD',  s: 'DCR/USD', isCrypto: true },
    { n: 'XVGUSD',  s: 'XVG/USD', isCrypto: true },
    { n: 'SCUSD',   s: 'SC/USD', isCrypto: true },
    { n: 'SNXUSD',  s: 'SNX/USD', isCrypto: true },
    { n: 'COMPUSD', s: 'COMP/USD', isCrypto: true },
    { n: 'MKRUSD',  s: 'MKR/USD', isCrypto: true },
    { n: 'AAVEUSD', s: 'AAVE/USD', isCrypto: true },
    { n: 'YFIUSD',  s: 'YFI/USD', isCrypto: true },
    { n: 'SUSHIUSD', s: 'SUSHI/USD', isCrypto: true },
    { n: 'CRVUSD',  s: 'CRV/USD', isCrypto: true },
    { n: 'RENUSD',  s: 'REN/USD', isCrypto: true },
    { n: 'KNCUSD',  s: 'KNC/USD', isCrypto: true },
    { n: 'BANDUSD', s: 'BAND/USD', isCrypto: true },
    { n: 'NMRUSD',  s: 'NMR/USD', isCrypto: true },
    { n: 'OCEANUSD', s: 'OCEAN/USD', isCrypto: true },
    { n: 'FETUSD',  s: 'FET/USD', isCrypto: true },
    { n: 'AGIXUSD', s: 'AGIX/USD', isCrypto: true },
    { n: 'BNBUSD',  s: 'BNB/USD', isCrypto: true },
    { n: 'CAKEUSD', s: 'CAKE/USD', isCrypto: true },
    { n: 'RUNEUSD', s: 'RUNE/USD', isCrypto: true },
    { n: 'ALGOUSD', s: 'ALGO/USD', isCrypto: true },
    { n: 'NEARUSD', s: 'NEAR/USD', isCrypto: true },
    { n: 'FLOWUSD', s: 'FLOW/USD', isCrypto: true },
    { n: 'APTUSD',  s: 'APT/USD', isCrypto: true },
    { n: 'OPUSD',   s: 'OP/USD', isCrypto: true },
    { n: 'ARBUSD',  s: 'ARB/USD', isCrypto: true },
    { n: 'SUIUSD',  s: 'SUI/USD', isCrypto: true },
    { n: 'INJUSD',  s: 'INJ/USD', isCrypto: true },
    { n: 'TIAUSD',  s: 'TIA/USD', isCrypto: true },
    { n: 'SEIUSD',  s: 'SEI/USD', isCrypto: true },
    { n: 'BLURUSD', s: 'BLUR/USD', isCrypto: true },
    { n: 'PYTHUSD', s: 'PYTH/USD', isCrypto: true },
    { n: 'JTOUSD',  s: 'JTO/USD', isCrypto: true },
    { n: 'ORDIUSD', s: 'ORDI/USD', isCrypto: true },
    { n: '1000SATSUSD', s: '1000SATS/USD', isCrypto: true },
    { n: 'BEAMUSD', s: 'BEAM/USD', isCrypto: true },
    { n: 'RNDRUSD', s: 'RNDR/USD', isCrypto: true },
    { n: 'IMXUSD',  s: 'IMX/USD', isCrypto: true },
    { n: 'MINAUSD', s: 'MINA/USD', isCrypto: true },
    { n: 'GALAUSD', s: 'GALA/USD', isCrypto: true },
    { n: 'AXSUSD',  s: 'AXS/USD', isCrypto: true },
    { n: 'APEUSD',  s: 'APE/USD', isCrypto: true },
    { n: 'ENSUSD',  s: 'ENS/USD', isCrypto: true },
    { n: 'LDOUSD',  s: 'LDO/USD', isCrypto: true },
    { n: 'STXUSD',  s: 'STX/USD', isCrypto: true },
    { n: 'CFXUSD',  s: 'CFX/USD', isCrypto: true },
    { n: 'KLAYUSD', s: 'KLAY/USD', isCrypto: true },
    { n: 'FTMUSD',  s: 'FTM/USD', isCrypto: true },
    { n: 'HBARUSD', s: 'HBAR/USD', isCrypto: true },
    { n: 'EGLDUSD', s: 'EGLD/USD', isCrypto: true },
    { n: 'QNTUSD',  s: 'QNT/USD', isCrypto: true },
    { n: 'ARUSD',   s: 'AR/USD', isCrypto: true },
    { n: 'ZILUSD',  s: 'ZIL/USD', isCrypto: true },
    { n: 'KSMUSD',  s: 'KSM/USD', isCrypto: true },
    { n: 'ANTUSD',  s: 'ANT/USD', isCrypto: true },
    { n: 'IOTXUSD', s: 'IOTX/USD', isCrypto: true },
    { n: 'CELOUSD', s: 'CELO/USD', isCrypto: true },
    { n: 'ANKRUSD', s: 'ANKR/USD', isCrypto: true },
    { n: 'SKLUSD',  s: 'SKL/USD', isCrypto: true },
    { n: 'SPELLUSD', s: 'SPELL/USD', isCrypto: true },
    { n: 'JOEUSD',  s: 'JOE/USD', isCrypto: true },
    { n: 'GMXUSD',  s: 'GMX/USD', isCrypto: true },
    { n: 'PENDLEUSD', s: 'PENDLE/USD', isCrypto: true },
    { n: 'SSVUSD',  s: 'SSV/USD', isCrypto: true },
    { n: 'FXSUSD',  s: 'FXS/USD', isCrypto: true },
    { n: 'LQTYUSD', s: 'LQTY/USD', isCrypto: true },
    { n: 'MASKUSD', s: 'MASK/USD', isCrypto: true },
];

// CRYPTO_PAIRS ko derive karo config se
const CRYPTO_PAIRS = PAIRS.filter(p => p.isCrypto).map(p => p.n);

const KEYS = [
    process.env.TD_KEY_1,  process.env.TD_KEY_2,  process.env.TD_KEY_3,
    process.env.TD_KEY_4,  process.env.TD_KEY_5,  process.env.TD_KEY_6,
    process.env.TD_KEY_7,  process.env.TD_KEY_8,  process.env.TD_KEY_9,
    process.env.TD_KEY_10, process.env.TD_KEY_11, process.env.TD_KEY_12,
    process.env.TD_KEY_13, process.env.TD_KEY_14, process.env.TD_KEY_15,
    process.env.TD_KEY_16
].filter(Boolean);

if (KEYS.length === 0) {
    console.error('[config] ❌ Koi bhi TD_KEY_* env variable nahi mili — scan nahi chalega!');
    process.exit(1);
}

console.log(`[config] ✅ ${KEYS.length} API keys loaded.`);

module.exports = {
    BOT_TOKEN:    requireEnv('BOT_TOKEN'),
    CHAT_ID:      requireEnv('CHAT_ID'),
    FIREBASE_URL: requireEnv('FIREBASE_URL'),
    KEYS,
    PAIRS,
    CRYPTO_PAIRS
};
