module.exports = [
    "AABS", "AAL", "AASL", "ABOT", "ABL", "ADAMS", "ADAM", "ADMM",
    "AGHA", "AGIL", "AGL", "AGP", "AHL", "AHTM", "AICL", "AIRLINK",
    "AKBL", "AKDHL", "AKDS", "ALNGR", "ALP", "ALTN", "AMBL", "AMRELI",
    "ANL", "APL", "ARPL", "ASL", "ASLC", "ASKARI", "ATLH", "ATLHRE",
    "ATLH-B", "ATRL", "AVN", "Awan", "AZM", "BAFL", "BAHL", "BAPL",
    "BATA", "BCCI", "BCL", "BCM", "BIPL", "BMA", "BMHL", "BOC", "BOD",
    "BOP", "BPL", "BRR", "BUXL", "BWCL",
    "CABB", "CACT", "CAMP", "CAPCO", "CAPM", "CASH", "CENI", "CEPB",
    "CHAL", "CHCC", "CHER", "CHIP", "CJPL", "CLOV", "CMC", "CNERGY",
    "COIN", "COLG", "CONC", "COSMO", "CPAL", "CPC", "CPI", "CPL",
    "CRSM", "CSAP", "CSIL", "CSM", "CTC", "CTM", "CYAN", "DAWH", "DCR",
    "DCTL", "DEBL", "DEW", "DFML", "DGKC", "DIN", "DLL", "DNCC", "DOL",
    "DOMF", "DWSM", "DYNO", "EFERT", "EFUG", "EFUL", "EIL", "ELCM",
    "EMCO", "ENGRO", "ENFR", "EPCL", "EPQL", "EXIDE", "FAEL", "FAFL",
    "FASM", "FATIMA", "FBBL", "FCCL", "FCEL", "FCON", "FCSC", "FDIB",
    "FECM", "FEROZ", "FFC", "FFL", "FFLM", "FFNG", "FHAM", "FIBLM",
    "FIL", "FIMM", "FIPS", "FLYNG", "FNBM", "FNDM", "FPL", "FRSM",
    "FTSM", "FUC", "FUDC",
    "GADT", "GAMON", "GATI", "GEL", "GEM", "GEN", "GFC", "GGGL", "GGL",
    "GHAL", "GHGL", "GHNI", "GHNL", "GHYL", "GICL", "GILD", "GLAXO",
    "GLOB", "GOC", "GRA", "GRR", "GTECH", "GTYR", "GUL", "HABIB",
    "HALEON", "HASCOL", "HBL", "HCAR", "HINO", "HMB", "HONRI", "HPFL",
    "HPL", "HRPL", "HSM", "HTL", "HUBC", "HUMNL", "HWQS", "IBLHL",
    "ICIBL", "ICL", "IGIHL", "IGIL", "ILP", "IMAGE", "IMC", "INDM",
    "INDU", "INIL", "INPC", "INT", "IPM", "ISL", "ITTEFAQ", "JDWS",
    "JGIC", "JKSM", "JOVC", "JPL", "JPM", "JSBL", "JSGCL", "JSIL",
    "JUBL", "KAPCO", "KASB", "KEC", "KEL", "KHAIR", "KHTC", "KML",
    "KNM", "KOHC", "KOHE", "KOSM", "KPAL", "KPT", "KSBP", "KTML",
    "LCCO", "LCI", "LEUL", "LINDE", "LOADS", "LOTCHEM", "LPGL", "LUCK",
    "MAC",
    "MACT", "MARI", "MAZ", "MCB", "MCBAH", "MDT", "MEBL", "MEFH",
    "MFF", "MFTM", "MIPH", "MILLAT", "MIR", "MIRA", "MLCF", "MMP",
    "MNFL", "MOD", "MOP", "MRE", "MRNS", "MSF", "MTL", "MUGHAL",
    "MUREB", "MZB", "NATF", "NAVA", "NBP", "NCL", "NCPL", "NDL", "NEP",
    "NESTLE", "NETSOL", "NEXT", "NEXUS", "NIL", "NINO", "NIP", "NIT",
    "NML", "NOM", "NPL", "NRL", "NSEC", "NTL", "NUST", "NVL", "NZO",
    "OBO", "OCT", "OGDC", "OLPL", "OPTIM", "ORIX", "ORL",
    "PACE", "PAEL", "PAKD", "PAKRI", "PAKT", "PARCO", "PASM", "PEL",
    "PIAA", "PIC", "PICT", "PINC", "PIOC", "PIRC", "PKFI", "PKGS",
    "PKGP", "PMPK", "PNSC", "POAM", "POL", "POWER", "PPL", "PRL",
    "PSMC", "PSO", "PTC", "PUNCH",
    "QC", "QMC", "QUAL", "RADCO", "RADO", "RAYA", "RCC", "REH", "RELI",
    "RICE", "RMPL", "ROSE",
    "SAIF", "SAMI", "SAPE", "SAPT", "SCBPL", "SCON", "SEARL", "SEC",
    "SECP", "SEL", "SFLP", "SGFL", "SGFM", "SGIC", "SHAM", "SHFA",
    "SHI", "SHM", "SHNI", "SILK", "SIM", "SIND", "SITARA", "SLIC",
    "SMBL", "SML", "SNGP", "SONA", "SONERI", "SPL", "SPWL", "SRC",
    "SSGC", "STCL", "STPL", "SURF", "SUT", "SYS",
    "TAND", "TATM", "TELE", "TEX", "TOMCL", "TPL", "TPLI", "TPLO",
    "TRE", "TRG", "TRI", "TSL", "TUS",
    "UBL", "UC", "UDPL", "UNIC", "UNI", "UNITY", "UNIV", "UTI",
    "VALU", "VANC", "VOLM", "WAK", "WAVE", "WIC", "WIN", "WOO", "WTL",
    "XER", "YAS", "YHL", "YHN", "YOUSEF", "ZAHID", "ZAM", "ZEAL", "ZIL", "ZTL"
];
